ex.py:
	The following is will logically result in infinite recursion.
	Usually max recursion limit is thrown when it is hit.
	
	Segmentation fault (core dumped) is thrown. Therefore,
	unauthorized memory access was attempted.